server:
  port: 8888
logging:
  path: logs
  file: mylog.log
spring:
  application:
    name: myTest
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url:  jdbc:mysql://192.168.31.250:3306/course
    username: yh
    password: 123456

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*